
const {
    GOOGLE_SHEETS_PRIVATE_KEY = '',
    SPREADSHEET_ID = '',
    GOOGLE_SHEETS_CLIENT_EMAIL = '',
} = process.env

module.exports = {
    GOOGLE_SHEETS_PRIVATE_KEY,
    SPREADSHEET_ID,
    GOOGLE_SHEETS_CLIENT_EMAIL,
}